{% set name = "rocm-device-libs" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/llvm-project/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: 12ce17dc920ec6dac0c5484159b3eec00276e4a5b301ab1250488db3b2852200
  patches:
    - patches/0001-Use-a-folder-inside-lib-for-bitcode-instead-of-top-l.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - rocm-cmake
    - zlib
    - clangdev 17.*
    - llvmdev 17.*
    - llvm

test:
  commands:
    - test -f $PREFIX/lib/amdgcn/bitcode/hip.bc

about:
  home: https://github.com/ROCm/ROCm-Device-Libs
  license: NCSA
  license_family: MIT
  license_file: LICENSE.TXT
  summary: 'ROCm Device libraries'

extra:
  recipe-maintainers:
    - isuruf
    - zklaus
