{% set name = "rocm-device-libs" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/llvm-project/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: 6bd9912441de6caf6b26d1323e1c899ecd14ff2431874a2f5883d3bc5212db34
  #patches:
  #  - patches/0001-Use-a-folder-inside-lib-for-bitcode-instead-of-top-l.patch

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - rocm-cmake
    - zlib
    - clangdev 17.*
    - llvmdev 17.*
    - llvm

test:
  commands:
    - test -f $PREFIX/lib/amdgcn/bitcode/hip.bc

about:
  home: https://github.com/ROCm/ROCm-Device-Libs
  license: NCSA
  license_family: MIT
  license_file: LICENSE.TXT
  summary: 'ROCm Device libraries'

extra:
  recipe-maintainers:
    - isuruf
    - zklaus
