{% set name = "rocm-device-libs" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/ROCm-Device-Libs/archive/refs/tags/rocm-6.0.2.tar.gz
  sha256: c6d88b9b46e39d5d21bd5a0c1eba887ec473a370b1ed0cebd1d2e910eedc5837

build:
  number: 0
  skip: True  # [not linux]
  #merge_build_host: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - clangdev 16.*
    - llvmdev 16.*
    - llvm

test:
  commands:
    - test -f $PREFIX/include/ocml.h

about:
  home: https://github.com/ROCm/ROCm-Device-Libs
  license: NCSA
  license_family: MIT
  license_file: LICENSE
  summary: 'ROCm Device libraries'

extra:
  recipe-maintainers:
    - isuruf
