{% set name = "rocm-device-libs" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RadeonOpenCompute/ROCm-Device-Libs/archive/roc-ocl-{{ version }}.tar.gz
  sha256: bce5da4adba4ea360cd4a8aff39d25d0d8a900bdd13aff0482b685bb495508f6

build:
  number: 0
  skip: true  # [not linux]
  merge_build_host: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - clangdev 9.*
    - llvmdev 9.*
    - llvm

test:
  commands:
    - test -f $PREFIX/include/ocml.h

about:
  home: https://github.com/RadeonOpenCompute/ROCm-Device-Libs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ROCm Device libraries

extra:
  recipe-maintainers:
    - isuruf
