{% set name = "rocm-device-libs" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RadeonOpenCompute/ROCm-Device-Libs/archive/roc-ocl-{{ version }}.tar.gz
  sha256: 05bf8c060db68cf5680a05b06ae7c4adefeb0f8d36f357accfa68e5d5185f72b

build:
  number: 0
  skip: True  # [not linux]
  merge_build_host: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - clangdev 9.*
    - llvmdev 9.*
    - llvm

test:
  commands:
    - test -f $PREFIX/include/ocml.h

about:
  home: https://github.com/RadeonOpenCompute/ROCm-Device-Libs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'ROCm Device libraries'

extra:
  recipe-maintainers:
    - isuruf
